server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: fundoonotes

  # ---------- POSTGRESQL ----------
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ---------- REDIS ----------
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}

  # ---------- RABBITMQ ----------
  rabbitmq:
    addresses: ${RABBITMQ_URL:}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:${RABBITMQ_USERNAME:guest}}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:false}
    connection-timeout: 5000ms




  # ---------- MAIL (for OTP & Reminders) ----------
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # ---------- GOOGLE OAUTH2 ----------
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# ---------- JWT ----------
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# ---------- APP-SPECIFIC ----------
app:
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:4200/login}

# ---------- SWAGGER / OPENAPI ----------
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
